apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: sre-app
spec:
  ingressClassName: traefik
  rules:
    - host: sre.nurzhqn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80