[sre_demo]
sre-vm ansible_host=YOUR_VM_IP ansible_user=YOUR_SSH_USER ansible_python_interpreter=/usr/bin/python3

[sre_demo:vars]
deploy_path=/opt/sre-app
git_repo=https://github.com/nurzhqn0/sre-app.git
git_version=main
app_domain=app.example.com
